---
# これを参考にitemを修正 https://github.com/sstephenson/ruby-build/wiki
- name: install dependencies
  yum: name={{ item }} state=latest # latestで最新に更新する
  with_items:
    - git
    - gcc
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
    - libxml2
    - ImageMagick
    - ImageMagick-devel
    - epel-release
    - mysql-devel
    - patch

# 先にgitを入れておかないとdry runでこけるので注意
- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
  become_user: "{{ rbenv_user }}"

- name: add ~.rbenv/bin to PATH
  lineinfile: >
    dest="~/.bash_profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  become_user: "{{ rbenv_user }}"

- name: eval rbenv init in ~/.bash_profile
  lineinfile: >
    dest="~/.bash_profile"
    line='eval "$(rbenv init -)"'
  become_user: "{{ rbenv_user }}"

- name: install ruby-build as rbenv plugin
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  become_user: "{{ rbenv_user }}"

- name: Check if version is installed ruby
  shell: bash -lc "rbenv versions | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_install
  changed_when: False # 実行時にchangedになる条件を設定、shellは叩くと常に実行されるのでchangedにカウントされる
  ignore_errors: yes
  become_user: "{{ rbenv_user }}"

- name: install ruby
  shell: bash -lc "rbenv install -v {{ rbenv_ruby_version }}" dest=~/.rbenv/shims/
  become_user: "{{ rbenv_user }}"
  when: rbenv_check_install|failed # rbenv_check_installがfailedの時だけ処理を実行する

- name: rbenv rehash
  shell: bash -lc "rbenv rehash"
  become_user: "{{ rbenv_user }}"
  when: rbenv_check_install|failed

- name: set default ruby version
  shell: bash -lc "rbenv global {{ rbenv_ruby_version }}"
  become_user: "{{ rbenv_user }}"
  when: rbenv_check_install|failed
