---
- hosts: all
  vars:
  remote_user: ec2-user
  become: yes

  roles:
    - { role: cloudwatch-logs }
  
  tasks:
    - name: Set hostname.
      lineinfile: dest=/etc/sysconfig/network regexp='^HOSTNAME' line='HOSTNAME=test-ec2' backup=yes
